"""BLE transport via `bleak` (install via `tether[ble]`).

Custom GATT service: one write characteristic (PC->MCU), one notify
characteristic (MCU->PC). Frame chunking/reassembly across the small BLE MTU
is handled entirely in this module — invisible above the dispatch layer.
See DESIGN.md § Transports.

This module is the PC-side (central/client) half. The peripheral half is
generated by tether.provisioning (`_BLE_BOOT_TEMPLATE`) and installed by
`tether provision ble`: a board provisioned that way advertises the service
below and serves the same status/upload/run control protocol wifi does, so
`mcu.connect("ble:<addr>")` uploads the runtime bundle over BLE itself
whenever the on-device hash doesn't match - no separate serial bootstrap
step. `BleControlChannel` below carries the length-prefixed framing that
control protocol runs over; connection.py's `_connect_ble` drives it.

`bleak` is client/central-only - there is no way to run a real local BLE
peripheral to test against, on any platform, with or without hardware. So
(unlike wifi, whose two halves meet over a real loopback socket) no test
exercises both halves of this protocol against each other. `BleStream`'s
bridging logic (MTU chunking, push-to-pull notification bridging) and
`BleControlChannel`'s framing are unit tested against a hand-written fake
matching bleak's documented async API shape (see tests/test_transport_ble.py);
the on-device half is tested separately, against a fake `bluetooth` module
under the real micropython interpreter (tests/ble_fakes.py). `connect()`
itself - the real bleak wiring - is not exercised by any test; there is no
way to do so without real BLE hardware and a real peripheral to connect to.
"""

from __future__ import annotations

import asyncio
import concurrent.futures
import hashlib
import hmac
import json
import queue
import struct
import threading
from typing import Any

from tether.marshalling.frame_auth import FrameAuthenticator

# Custom 128-bit UUIDs for tether's GATT service - arbitrary but fixed, so
# the on-device peripheral (provisioning.py's _BLE_BOOT_TEMPLATE, which
# hardcodes the same three strings - see
# test_ble_boot_uuids_match_the_pc_side_transport) and this PC-side client
# agree on what to look for. Generated once, never to be changed without bumping
# PROTOCOL_VERSION (connection.py) - an unrecognized UUID looks identical
# to "wrong device" from this module's point of view either way.
SERVICE_UUID = "6e400001-b5a3-f393-e0a9-e50e24dcca9e"
WRITE_CHAR_UUID = "6e400002-b5a3-f393-e0a9-e50e24dcca9e"
NOTIFY_CHAR_UUID = "6e400003-b5a3-f393-e0a9-e50e24dcca9e"

DEFAULT_TIMEOUT = 10.0

# BLE ATT header: 1-byte opcode + 2-byte handle - subtracted from the
# negotiated MTU to get the usable payload size per GATT write.
_ATT_HEADER_OVERHEAD = 3

# Half of wifi's DEFAULT_TAG_LENGTH (16) - BLE's chunking is transparent
# to frame size (unlike wifi's hard MAX_CONTROL_FRAME_SIZE ceiling), so
# this isn't a correctness constraint, it's a latency one: every BLE write
# is a full round trip, and this halves how often the envelope's overhead
# spills a small frame into one more chunk. See DESIGN.md's BLE row,
# "Per-frame authentication (2026-08-06)" for the full tradeoff.
BLE_TAG_LENGTH = 8

_LENGTH_PREFIX = struct.Struct(">I")


class BleStream:
    """Duplex stream bridging a connected `bleak.BleakClient` (async,
    foreign event loop) to the plain synchronous read()/write() contract
    tether.dispatch.Dispatcher expects - same shape as SerialStream/
    WifiStream, but BLE is push-based (notifications arrive via a callback)
    rather than pull-based (a blocking read() call), so read() is backed by
    a thread-safe queue fed by `on_notify` instead of calling into the
    client directly.
    """

    def __init__(self, client: Any, loop: asyncio.AbstractEventLoop, write_char_uuid: str) -> None:
        self._client = client
        self._loop = loop
        self._write_char_uuid = write_char_uuid
        self._queue: queue.Queue[bytes] = queue.Queue()
        self._send_auth: FrameAuthenticator | None = None
        self._recv_auth: FrameAuthenticator | None = None

    def enable_authentication(
        self, send_auth: FrameAuthenticator, recv_auth: FrameAuthenticator
    ) -> None:
        """Switch every subsequent read()/write() on this stream to per-frame
        HMAC authentication, using the EXACT authenticator instances given -
        not derived fresh from a session key. Call once, right before handing
        this stream to Dispatcher for run mode, passing the same instances
        BleControlChannel already used for status/upload on this connection
        (channel._send_auth/channel._recv_auth) - BLE reuses one physical
        connection across every mode (see DESIGN.md's BLE row), so the replay
        counters must continue from wherever the control channel left them,
        not restart at 0.
        """
        self._send_auth = send_auth
        self._recv_auth = recv_auth

    def read(self, timeout: float | None = None) -> bytes:
        """Return the next chunk of device->PC bytes (b"" once the link
        drops - see signal_closed).

        `timeout=None` (the default) blocks indefinitely, which is the
        correct contract for the long-lived RPC stream the Dispatcher
        owns: "no data for N seconds" is normal on an idle session, and
        only an empty read means disconnected (same handoff shape as
        serial's `ser.timeout = None` and wifi's `switch_to_blocking`).

        A bounded `timeout` is for the synchronous control exchange that
        happens BEFORE that handoff (BleControlChannel below) - a device
        that stays connected but never answers must fail rather than hang
        forever. Expiry raises OSError rather than letting queue.Empty
        escape: every caller above here is written against the
        OSError/empty-bytes contract the serial and wifi streams use.
        """
        if self._recv_auth is None:
            if timeout is None:
                return self._queue.get()
            try:
                return self._queue.get(timeout=timeout)
            except queue.Empty:
                raise OSError(f"timed out after {timeout}s waiting for BLE data") from None
        return self._read_authenticated_chunk(timeout)

    def _read_authenticated_chunk(self, timeout: float | None) -> bytes:
        header = self._recv_exact_raw(_LENGTH_PREFIX.size, timeout)
        if not header:
            return b""
        (length,) = _LENGTH_PREFIX.unpack(header)
        body = self._recv_exact_raw(length, timeout)
        if not body:
            return b""
        assert self._recv_auth is not None
        return self._recv_auth.unwrap(body)

    def _recv_exact_raw(self, n: int, timeout: float | None) -> bytes:
        buf = b""
        while len(buf) < n:
            if timeout is None:
                chunk = self._queue.get()
            else:
                try:
                    chunk = self._queue.get(timeout=timeout)
                except queue.Empty:
                    raise OSError(f"timed out after {timeout}s waiting for BLE data") from None
            if not chunk:
                return b""
            buf += chunk
        return buf

    def write(self, data: bytes, timeout: float | None = None) -> None:
        """`timeout=None` (the default) blocks indefinitely - correct for
        the long-lived RPC stream the Dispatcher owns, same reasoning as
        `read()`'s default. A bounded `timeout` is for the synchronous
        control exchange (BleControlChannel) - a peripheral that stops
        acknowledging ATT writes mid-exchange must fail rather than hang
        this call (and, transitively, the caller's whole process) forever.
        Raises OSError on expiry, matching read()'s contract - this used
        to have no timeout at all, silently inheriting whatever
        `.result()`'s own default (block forever) did.
        """
        if self._send_auth is not None:
            data = self._send_auth.wrap(data)
        # GATT writes are capped by the negotiated ATT MTU - split anything
        # larger into multiple writes. FrameDecoder (marshalling/__init__.py)
        # already reassembles arbitrarily-chunked reads into whole frames on
        # the Dispatcher side, so read()/on_notify below need no equivalent
        # reassembly logic - only the write side needs to actively chunk,
        # since BLE (unlike a TCP socket or serial port) will reject or
        # truncate a write larger than the MTU rather than accepting and
        # buffering it.
        usable = max(self._client.mtu_size - _ATT_HEADER_OVERHEAD, 1)
        chunks = [data[i : i + usable] for i in range(0, len(data), usable)]

        async def _write_all() -> None:
            # BLE allows only one outstanding ATT request at a time - each
            # chunk must be awaited (not just sent) before the next is
            # written, or an out-of-order ack (or a controller/OS BLE stack
            # that doesn't strictly serialize concurrent requests) could
            # corrupt the frame being reassembled on the far side. This is a
            # correctness requirement, not just a convenient way to get
            # sequencing - do not parallelize these writes.
            #
            # response=True (write-with-response) trades throughput for a
            # per-write delivery guarantee from the peripheral. Kept
            # deliberately: this project has no real BLE hardware to
            # validate write-without-response's actual reliability
            # characteristics across platforms/controllers, and DESIGN.md's
            # wire protocol has no independent per-frame ack of its own to
            # fall back on if a written chunk were silently dropped.
            for chunk in chunks:
                await self._client.write_gatt_char(self._write_char_uuid, chunk, response=True)

        # One cross-thread hop for the whole write() call (one Future, one
        # event-loop wakeup) rather than one per chunk - the sequencing
        # above already happens entirely within this single coroutine on
        # the loop's own thread.
        future = asyncio.run_coroutine_threadsafe(_write_all(), self._loop)
        try:
            future.result(timeout=timeout)
        except concurrent.futures.TimeoutError:
            # The coroutine is still running on the loop's thread after
            # this - cancel() only prevents future.result() from waiting
            # on it further, matching connect()'s own documented handling
            # of this exact race (see its own TimeoutError comment below).
            future.cancel()
            raise OSError(f"timed out after {timeout}s writing BLE data") from None

    def on_notify(self, _sender: Any, data: bytearray) -> None:
        """Registered as the notify characteristic's callback - matches
        bleak's `Callable[[BleakGATTCharacteristic, bytearray], None]`
        signature. bleak invokes this on its own event-loop thread;
        queue.Queue.put is thread-safe so no call_soon_threadsafe/marshalling
        is needed here (unlike MockTransport's asyncio.Queue bridge in
        transports/mock.py, which needs it because asyncio.Queue isn't
        thread-safe - queue.Queue is a different tool for exactly this
        reason).
        """
        self._queue.put(bytes(data))

    def signal_closed(self) -> None:
        """Called from bleak's `disconnected_callback` - pushes the same
        "transport closed" signal Dispatcher._run_reader already looks for
        (an empty read()), so a BLE disconnect fails loud through the exact
        same path as a dead serial port or closed socket, rather than
        needing BLE-specific disconnect handling anywhere above this
        module.
        """
        self._queue.put(b"")

    def close(self) -> None:
        asyncio.run_coroutine_threadsafe(self._client.disconnect(), self._loop).result()
        # connect() gave this stream's event loop its own dedicated thread
        # purely to run bleak's async API (unlike wifi/serial, no blocking
        # syscall justifies leaving that thread alive once disconnected) -
        # stop it so close() doesn't leak a thread on every call.
        self._loop.call_soon_threadsafe(self._loop.stop)


# Same resource-safety bound as wifi's control channel (transports/wifi.py)
# and the RPC layer's MAX_FRAME_SIZE - a declared length this large would
# risk buffering an unbounded amount of attacker/bug-controlled data before
# anything is validated.
MAX_CONTROL_FRAME_SIZE = 1 << 16  # 64 KiB


class BleControlChannel:
    """Length-prefixed JSON/bytes framing over an already-connected
    BleStream, for the preamble/status/upload control protocol - mirrors
    transports/wifi.py's free-function helpers, but stateful:
    BleStream.read() returns whatever one GATT notification happened to
    carry (not a caller-chosen byte count, unlike socket.recv(n)), so
    leftover bytes from one frame must persist into the next read - this
    class holds that buffer.

    One instance per BleStream, reused across every preamble on that
    connection - status -> upload -> run all share it (see the design's
    one-connection decision: BLE connection setup is too costly to redo
    per mode, unlike wifi's cheap TCP handshake).

    `timeout` bounds every read AND write this channel makes (per call,
    like a socket timeout - wifi's control channel gets the same
    semantics from `socket.settimeout`). It is deliberately not shared
    with the underlying BleStream, which stays unbounded-blocking for the
    Dispatcher's own reads/writes once the control exchange is over and
    the raw stream is handed off - see BleStream.read's/write's
    docstrings. Pass None only if a caller genuinely wants to wait
    forever.
    """

    def __init__(self, stream: BleStream, *, timeout: float | None = DEFAULT_TIMEOUT) -> None:
        self._stream = stream
        self._timeout = timeout
        self._buffer = b""
        # Unlike wifi (fresh connection, fresh nonce, per mode), one BLE
        # connection is reused across every mode - so only the FIRST
        # send_preamble() call on a given channel does the nonce-challenge
        # round trip; every later call on the same (already-authenticated)
        # connection just sends {mode}. See send_preamble's own docstring
        # and _BLE_BOOT_TEMPLATE's matching device-side state.
        self._authenticated = False
        self._session_key: bytes | None = None
        self._send_auth: FrameAuthenticator | None = None
        self._recv_auth: FrameAuthenticator | None = None

    def _recv_exact(self, n: int) -> bytes:
        while len(self._buffer) < n:
            chunk = self._stream.read(self._timeout)
            if not chunk:
                raise OSError("connection closed while reading a frame")
            self._buffer += chunk
        result, self._buffer = self._buffer[:n], self._buffer[n:]
        return result

    def _json_frame_bytes(self, payload: dict[str, Any]) -> bytes:
        body = json.dumps(payload).encode("utf-8")
        return _LENGTH_PREFIX.pack(len(body)) + body

    def _bytes_frame_bytes(self, data: bytes) -> bytes:
        return _LENGTH_PREFIX.pack(len(data)) + data

    def send_json_frame(self, payload: dict[str, Any]) -> None:
        self._stream.write(self._json_frame_bytes(payload), self._timeout)

    def read_json_frame(self) -> dict[str, Any]:
        header = self._recv_exact(_LENGTH_PREFIX.size)
        (length,) = _LENGTH_PREFIX.unpack(header)
        if length > MAX_CONTROL_FRAME_SIZE:
            raise OSError(f"control frame too large: declared {length} bytes")
        body = self._recv_exact(length)
        return json.loads(body.decode("utf-8"))

    def send_bytes_frame(self, data: bytes) -> None:
        self._stream.write(self._bytes_frame_bytes(data), self._timeout)

    def read_bytes_frame(self) -> bytes:
        header = self._recv_exact(_LENGTH_PREFIX.size)
        (length,) = _LENGTH_PREFIX.unpack(header)
        if length > MAX_CONTROL_FRAME_SIZE:
            raise OSError(f"control frame too large: declared {length} bytes")
        return self._recv_exact(length)

    def _read_authenticated_body(self) -> bytes:
        header = self._recv_exact(_LENGTH_PREFIX.size)
        (length,) = _LENGTH_PREFIX.unpack(header)
        if length > MAX_CONTROL_FRAME_SIZE:
            raise OSError(f"authenticated frame too large: declared {length} bytes")
        return self._recv_exact(length)

    def send_authenticated_json_frame(self, payload: dict[str, Any]) -> None:
        assert self._send_auth is not None
        self._stream.write(self._send_auth.wrap(self._json_frame_bytes(payload)), self._timeout)

    def read_authenticated_json_frame(self) -> dict[str, Any]:
        assert self._recv_auth is not None
        inner = self._recv_auth.unwrap(self._read_authenticated_body())
        (length,) = _LENGTH_PREFIX.unpack_from(inner, 0)
        body = inner[_LENGTH_PREFIX.size : _LENGTH_PREFIX.size + length]
        return json.loads(body.decode("utf-8"))

    def send_authenticated_bytes_frame(self, data: bytes) -> None:
        assert self._send_auth is not None
        self._stream.write(self._send_auth.wrap(self._bytes_frame_bytes(data)), self._timeout)

    def read_authenticated_bytes_frame(self) -> bytes:
        assert self._recv_auth is not None
        inner = self._recv_auth.unwrap(self._read_authenticated_body())
        (length,) = _LENGTH_PREFIX.unpack_from(inner, 0)
        return inner[_LENGTH_PREFIX.size : _LENGTH_PREFIX.size + length]

    def send_preamble(self, mode: str, secret: str | None) -> bytes | None:
        """Send the connection preamble (mode, plus a nonce-challenge
        response on the FIRST call this channel makes) and wait for the
        device's ack. Raises WifiAuthError if the device rejects it -
        same error type wifi's send_preamble uses (see transports/wifi.py),
        reused rather than adding a BLE-specific auth error class.

        The device sends one nonce per physical connection, immediately
        after accepting it and before reading any preamble - not per mode,
        since a BLE connection is reused across status -> upload -> run
        (see the design's one-connection decision, BleControlChannel's own
        class docstring, and _BLE_BOOT_TEMPLATE's matching device-side
        state). This channel mirrors that: the nonce is read and answered
        exactly once (`self._authenticated` below), and every later
        send_preamble() call on the same channel sends just `{mode}` - the
        device already knows this connection is authenticated and doesn't
        expect (or check) a response on those later preambles.

        Returns the connection's session key for per-frame authentication
        (derived once, on the first call, and cached - every later call on
        this same channel returns the SAME key, matching the domain-separated
        derivation wifi's send_preamble uses), or None when `secret` is None.
        """
        from tether.errors import WifiAuthError

        if not self._authenticated:
            nonce_frame = self.read_json_frame()
            nonce = bytes.fromhex(nonce_frame["nonce"])
            if secret is not None:
                response = hmac.new(secret.encode(), nonce, hashlib.sha256).hexdigest()
                self._session_key = hmac.new(
                    secret.encode(), b"tether-frame-key" + nonce, hashlib.sha256
                ).digest()
                self._send_auth = FrameAuthenticator(self._session_key, BLE_TAG_LENGTH)
                self._recv_auth = FrameAuthenticator(self._session_key, BLE_TAG_LENGTH)
            else:
                response = None
            self.send_json_frame({"mode": mode, "response": response})
            self._authenticated = True
        else:
            self.send_json_frame({"mode": mode})
        ack = self.read_json_frame()
        if not ack.get("ok", False):
            raise WifiAuthError(ack.get("error") or "connection rejected by device")
        return self._session_key


def connect(address: str, *, timeout: float = DEFAULT_TIMEOUT) -> BleStream:
    """Connect to a board advertising tether's custom GATT service
    (SERVICE_UUID/WRITE_CHAR_UUID/NOTIFY_CHAR_UUID above) - i.e. one
    provisioned by `tether provision ble`.

    Returns the raw duplex stream only. The mode preamble, hash check and
    upload-if-needed all happen above this, over BleControlChannel (see
    connection.py's _connect_ble) - this function opens the link and
    nothing more.

    `timeout` bounds the BLE connect itself. It is deliberately NOT
    applied to the returned stream's reads, which stay unbounded: this
    stream eventually becomes the long-lived Dispatcher RPC stream (see
    BleStream.read's docstring). Callers doing bounded control-exchange
    reads before that handoff pass their own timeout to BleControlChannel.

    bleak's client API is async; this bridges it to BleStream's plain
    synchronous contract the same way transports/mock.py bridges chunk 6's
    real asyncio-based dispatch loop to CPython - a dedicated background
    thread owns its own event loop and the BleakClient for this
    connection's whole lifetime.
    """
    import bleak  # optional extra (tether[ble]) - fails loud with the
    # interpreter's own clear ModuleNotFoundError if not installed, same as
    # transports/serial.py's lazy `from serial.tools import list_ports`.

    result: concurrent.futures.Future[BleStream] = concurrent.futures.Future()

    def _run() -> None:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

        async def _setup() -> None:
            stream: BleStream | None = None

            def _on_disconnect(_client: Any) -> None:
                if stream is not None:
                    stream.signal_closed()

            try:
                client = bleak.BleakClient(address, disconnected_callback=_on_disconnect)
                await client.connect(timeout=timeout)
                stream = BleStream(client, loop, WRITE_CHAR_UUID)
                await client.start_notify(NOTIFY_CHAR_UUID, stream.on_notify)
            except BaseException as exc:  # noqa: BLE001 - propagated via the future below, never swallowed
                try:
                    result.set_exception(exc)
                except concurrent.futures.InvalidStateError:
                    pass  # caller already gave up (see the `except TimeoutError` below)
                loop.call_soon_threadsafe(loop.stop)
                return

            try:
                result.set_result(stream)
            except concurrent.futures.InvalidStateError:
                # The caller's result(timeout=...) below already gave up
                # before this connect attempt finished - don't strand a
                # live, unmanaged BLE connection nothing will ever close.
                # Most peripherals accept only one central connection at a
                # time, so leaving this open could block every future
                # (re)connect attempt, not just leak a thread.
                await client.disconnect()
                loop.call_soon_threadsafe(loop.stop)

        loop.create_task(_setup())
        loop.run_forever()

    threading.Thread(target=_run, daemon=True).start()
    try:
        return result.result(timeout=timeout + 5.0)
    except concurrent.futures.TimeoutError:
        # Future.cancel() on a still-pending future transitions it to
        # CANCELLED, so _setup()'s later set_result()/set_exception() call
        # (above) observes InvalidStateError and cleans up instead of
        # silently succeeding into a connection nobody holds a reference
        # to - see its own comment. No-op (returns False) if _setup()
        # already finished first; that race is exactly what the
        # InvalidStateError check on the other side is for.
        result.cancel()
        raise
